import { Product } from "./types";

/**
 * PRODUCT DATA
 * ------------
 * Ethnic Dresses Collection for LAYORA
 */
export const products: Product[] = [
  {
    id: "ethnic-001",
    name: "Blush Vanilla Festive Suit",
    slug: "blush-vanilla",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "An exquisite pastel festive ensemble in soft blush vanilla featuring delicate neckline embroidery and fine hand-worked detailing on premium fabric.",
    details: [
      "Premium embroidered festive fabric",
      "Hand-finished neckline & sleeve borders",
      "Includes matching dupatta & tailored trousers",
      "Dry clean recommended",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blush Vanilla"],
    images: [
      "/products/ethnic/blush-vanilla/1.jpeg",
      "/products/ethnic/blush-vanilla/2.jpeg",
      "/products/ethnic/blush-vanilla/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 15,
    isNew: true,
  },
  {
    id: "ethnic-002",
    name: "Coral Breeze Embroidered Ensemble",
    slug: "coral-breeze",
    category: "dresses",
    subcategory: null,
    price: 8000,
    originalPrice: 9000,
    currency: "PKR",
    description:
      "Vibrant coral ethnic outfit adorned with floral thread work and an airy, flattering silhouette perfect for summer occasions and festive gatherings.",
    details: [
      "Breathable luxury fabric",
      "Detailed floral thread embroidery",
      "Stitched 3-piece complete suit",
      "Gentle wash or dry clean",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Coral Breeze"],
    images: [
      "/products/ethnic/coral-breeze/1.jpeg",
      "/products/ethnic/coral-breeze/2.jpeg",
      "/products/ethnic/coral-breeze/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 12,
    isNew: true,
  },
  {
    id: "ethnic-003",
    name: "Crimson Fringe Statement Dress",
    slug: "crimson-fringe",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "A striking deep crimson ethnic dress accented with intricate fringe tassels and modern tailored cuts for a bold, celebratory look.",
    details: [
      "Rich crimson dyed luxury blend",
      "Artisanal fringe & tassel accents",
      "Includes formal trousers & embellished dupatta",
      "Dry clean only",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Crimson Red"],
    images: [
      "/products/ethnic/crimson-fringe/1.jpeg",
      "/products/ethnic/crimson-fringe/2.jpeg",
      "/products/ethnic/crimson-fringe/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 10,
    isNew: true,
  },
  {
    id: "ethnic-004",
    name: "Earthy Tassel Raw Silk Ensemble",
    slug: "earthy-tassel",
    category: "dresses",
    subcategory: null,
    price: 8000,
    originalPrice: 9000,
    currency: "PKR",
    description:
      "Sophisticated earth-toned dress styled with subtle embroidery and handcrafted tassel details for understated modern luxury.",
    details: [
      "Earth-toned premium blend",
      "Handcrafted hanging tassels along hem & neckline",
      "Contemporary straight silhouette",
      "Dry clean recommended",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Earthy Olive"],
    images: [
      "/products/ethnic/earthy-tassel/1.jpeg",
      "/products/ethnic/earthy-tassel/2.jpeg",
      "/products/ethnic/earthy-tassel/3.jpeg",
    ],
    featured: false,
    available: true,
    stock: 14,
  },
  {
    id: "ethnic-005",
    name: "Jellyfish Organza Dream",
    slug: "jellyfish",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "An ethereal and flowing ethnic silhouette inspired by organic waves, finished with sheer sleeves and delicate shimmer border work.",
    details: [
      "Lustrous organza with soft inner lining",
      "Fluid draped sleeves and neckline",
      "Embellished delicate borders",
      "Dry clean only",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Oceanic Lilac"],
    images: [
      "/products/ethnic/jellyfish/1.jpeg",
      "/products/ethnic/jellyfish/2.jpeg",
      "/products/ethnic/jellyfish/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 8,
    isNew: true,
  },
  {
    id: "ethnic-006",
    name: "Lemonade Festive Kurti Set",
    slug: "lemonade",
    category: "dresses",
    subcategory: null,
    price: 8000,
    originalPrice: 9000,
    currency: "PKR",
    description:
      "Bright and cheerful pastel yellow dress with clean stitching and contrast thread accents, ideal for daytime festivities and Eid celebrations.",
    details: [
      "Lightweight summer luxury lawn",
      "Delicate thread work on placket and hem",
      "Comfortable relaxed silhouette",
      "Hand wash cold",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Lemonade Yellow"],
    images: [
      "/products/ethnic/lemonade/1.jpeg",
      "/products/ethnic/lemonade/2.jpeg",
      "/products/ethnic/lemonade/3.jpeg",
    ],
    featured: false,
    available: true,
    stock: 18,
  },
  {
    id: "ethnic-007",
    name: "Lotus Blossom Luxury Pret",
    slug: "lotus",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "Graceful floral motifs reminiscent of fresh lotus blooms, paired with an intricately printed and embroidered organza dupatta.",
    details: [
      "Fine jacquard & lawn base",
      "Intricate floral embroidery",
      "Embroidered organza dupatta with lace trim",
      "Dry clean recommended",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Lotus Pink"],
    images: [
      "/products/ethnic/lotus/1.jpeg",
      "/products/ethnic/lotus/2.jpeg",
      "/products/ethnic/lotus/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 11,
  },
  {
    id: "ethnic-008",
    name: "Midnight Bloom Evening Formal",
    slug: "midnight-bloom",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "Dramatic midnight black formal suit covered with luminous tonal embroidery, fine sequins, and scalloped lace borders.",
    details: [
      "Rich midnight black premium fabric",
      "Zari and sequin hand embellishments",
      "Complete 3-piece formal outfit",
      "Dry clean only",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Midnight Black"],
    images: [
      "/products/ethnic/midnight-bloom/1.jpeg",
      "/products/ethnic/midnight-bloom/2.jpeg",
      "/products/ethnic/midnight-bloom/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 9,
    isNew: true,
  },
  {
    id: "ethnic-009",
    name: "Oreo Cookie Monochromatic Suit",
    slug: "oreo-cookie",
    category: "dresses",
    subcategory: null,
    price: 8000,
    originalPrice: 9000,
    currency: "PKR",
    description:
      "Chic black and ivory monochrome ethnic set with geometric borders and contrast lace finishes for timeless, effortless style.",
    details: [
      "Premium monochrome lawn/cotton",
      "Geometric lace borders on hem and sleeves",
      "Includes matching straight trousers",
      "Machine wash gentle",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black & Ivory"],
    images: [
      "/products/ethnic/oreo-cookie/1.jpeg",
      "/products/ethnic/oreo-cookie/2.jpeg",
      "/products/ethnic/oreo-cookie/3.jpeg",
    ],
    featured: false,
    available: true,
    stock: 16,
  },
  {
    id: "ethnic-010",
    name: "Parcely Pastel Classic",
    slug: "parcely",
    category: "dresses",
    subcategory: null,
    price: 8000,
    originalPrice: 9000,
    currency: "PKR",
    description:
      "Understated elegance in soft soothing pastel tones, designed with tailored pintucks and subtle embroidery on cuffs and neckline.",
    details: [
      "Soft luxury cotton blend",
      "Tailored pintucks & pleats",
      "Breathable and comfortable all-day wear",
      "Machine wash cold",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Pastel Mint"],
    images: [
      "/products/ethnic/parcely/1.jpeg",
      "/products/ethnic/parcely/2.jpeg",
      "/products/ethnic/parcely/3.jpeg",
    ],
    featured: false,
    available: true,
    stock: 20,
  },
  {
    id: "ethnic-011",
    name: "Pink Vibes Embroidered Outfit",
    slug: "pink-vibes",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "Youthful and vibrant pink dress featuring rich thread embroidery along the hem and sleeves with matching flared trousers.",
    details: [
      "Vibrant dyed premium fabric",
      "High-density thread embroidery",
      "Flared matching bottoms & dupatta",
      "Dry clean recommended",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Rose Pink"],
    images: [
      "/products/ethnic/pink-vibes/1.jpeg",
      "/products/ethnic/pink-vibes/2.jpeg",
      "/products/ethnic/pink-vibes/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 14,
  },
  {
    id: "ethnic-012",
    name: "Sand Neutral Minimalist Suit",
    slug: "sand",
    category: "dresses",
    subcategory: null,
    price: 8000,
    originalPrice: 9000,
    currency: "PKR",
    description:
      "Warm sand and beige hues crafted in a minimalist ethnic cut with wooden button details and rich textured fabric.",
    details: [
      "Textured breathable fabric",
      "Minimalist tonal stitch work",
      "Comfortable relaxed silhouette",
      "Hand wash cold",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Warm Sand"],
    images: [
      "/products/ethnic/sand/1.jpeg",
      "/products/ethnic/sand/2.jpeg",
      "/products/ethnic/sand/3.jpeg",
    ],
    featured: false,
    available: true,
    stock: 22,
  },
  {
    id: "ethnic-013",
    name: "Starry Wave Luxury Pret",
    slug: "starry-wave",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "A show-stopping navy blue and silver ensemble with delicate glitter waves and heavy border embellishments for festive events.",
    details: [
      "Navy chiffon/silk base",
      "Metallic thread & starry sequin work",
      "Includes embellished formal dupatta & trousers",
      "Dry clean only",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy & Silver"],
    images: [
      "/products/ethnic/starry-wave/1.jpeg",
      "/products/ethnic/starry-wave/2.jpeg",
      "/products/ethnic/starry-wave/3.jpeg",
      "/products/ethnic/starry-wave/4.jpeg",
    ],
    featured: true,
    available: true,
    stock: 7,
    isNew: true,
  },
  {
    id: "ethnic-014",
    name: "Sweetheart Fuchsia Festive Gown",
    slug: "sweetheart-fuchsia",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "Rich fuchsia ethnic gown featuring a sweetheart cut neckline, gold gota work, and a voluminous flared kali cut.",
    details: [
      "Pure georgette & shimmer lining",
      "Gota patti and zari detailing",
      "Voluminous kali silhouette",
      "Dry clean only",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Fuchsia"],
    images: [
      "/products/ethnic/sweetheart-fuchsia/1.jpeg",
      "/products/ethnic/sweetheart-fuchsia/2.jpeg",
      "/products/ethnic/sweetheart-fuchsia/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 10,
  },
  {
    id: "ethnic-015",
    name: "Twilight Velvet Elegance",
    slug: "twilight",
    category: "dresses",
    subcategory: null,
    price: 9000,
    originalPrice: 10000,
    currency: "PKR",
    description:
      "Deep twilight dusk palette with intricate resham embroidery and organza cutwork borders for evening occasions.",
    details: [
      "Formal silk/velvet blend",
      "Resham thread and tilla work",
      "Cutwork organza borders on sleeves and hem",
      "Dry clean only",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Twilight Plum"],
    images: [
      "/products/ethnic/twilight/1.jpeg",
      "/products/ethnic/twilight/2.jpeg",
      "/products/ethnic/twilight/3.jpeg",
    ],
    featured: true,
    available: true,
    stock: 8,
  },
  {
    id: "case-001",
    name: "BTS Dynamite Pop Art Case",
    slug: "bts-dynamite-pop-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Vibrant K-Pop inspired graphic phone case featuring dynamic BTS artwork with high-gloss finish and military-grade drop protection.",
    details: [
      "Impact-resistant dual layer polycarbonate shell",
      "Vivid fade-proof UV sublimation print",
      "Raised 1.2mm camera bezel & screen rim",
      "Wireless charging & MagSafe compatible",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/bts.jpeg"],
    featured: true,
    available: true,
    stock: 25,
    isNew: true,
  },
  {
    id: "case-002",
    name: "Buba Funky Cartoon Case",
    slug: "buba-funky-cartoon-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Playful and whimsical character art case designed to add a fun pop of personality to your daily essentials.",
    details: [
      "Shock-absorbing TPU inner cushion",
      "Scratch-resistant satin texture",
      "Precise cutouts for speakers and ports",
      "Lightweight slim-fit profile",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/buba.jpeg"],
    featured: true,
    available: true,
    stock: 20,
    isNew: true,
  },
  {
    id: "case-003",
    name: "Cutiepie Anime Pop Case",
    slug: "cutiepie-anime-pop-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Super-cute Japanese Kawaii aesthetic phone cover with soft pastel accents and durable edge-to-edge impact protection.",
    details: [
      "Anti-yellowing polymer technology",
      "Ultra-vibrant high-resolution colors",
      "Reinforced corner bumper protection",
      "Comfortable non-slip ergonomic grip",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/cutiepie.jpeg"],
    featured: false,
    available: true,
    stock: 18,
    isNew: true,
  },
  {
    id: "case-004",
    name: "Electric Rock Guitar Pop Case",
    slug: "electric-rock-guitar-pop-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Bold retro-rock inspired electric guitar graphic case crafted for music enthusiasts and vintage aesthetic lovers.",
    details: [
      "Dual-layer hybrid impact shell",
      "Detailed guitar vector art print",
      "Textured tactile side grips",
      "Drop-tested up to 8 feet",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/guitar.jpeg"],
    featured: true,
    available: true,
    stock: 15,
    isNew: true,
  },
  {
    id: "case-005",
    name: "LOVE Graffiti Street Art Case",
    slug: "love-graffiti-street-art-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Urban pop-art typography displaying dynamic street-style graffiti lettering with vivid neon and monochrome contrasts.",
    details: [
      "Matte anti-fingerprint coating",
      "Durable shock-resistant bumper",
      "Wireless charging friendly",
      "Engineered for snug snap-on fit",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/love.jpeg"],
    featured: true,
    available: true,
    stock: 30,
    isNew: true,
  },
  {
    id: "case-006",
    name: "Cyber Ninja Anime Case",
    slug: "cyber-ninja-anime-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Futuristic neo-Tokyo cyber ninja illustration with glowing neon contrasts, designed for sleek anime styling and heavy-duty defense.",
    details: [
      "Military standard drop protection",
      "Precision camera cutout with raised rim",
      "UV-cured scratch-resistant backplate",
      "Responsive tactile button overlays",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/ninja.jpeg"],
    featured: true,
    available: true,
    stock: 22,
    isNew: true,
  },
  {
    id: "case-007",
    name: "Pink Stardust Celestial Case",
    slug: "pink-stardust-celestial-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Dreamy pink celestial landscape with shimmering cosmic dust motifs, perfect for modern chic everyday elegance.",
    details: [
      "Crystal-clear resin with glitter infusion",
      "Non-slip ergonomic contour",
      "Shock-dispersing air-cushion corners",
      "Fade-proof deep dye finish",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/pink-stardust.png"],
    featured: true,
    available: true,
    stock: 25,
    isNew: true,
  },
  {
    id: "case-008",
    name: "Puma Fierce Predator Case",
    slug: "puma-fierce-predator-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Intense wildlife graphic showcasing a fierce puma in stylized modern pop-art brush strokes.",
    details: [
      "Hybrid rigid PC back and flexible TPU edges",
      "High-contrast dynamic color saturation",
      "Ultra-slim 1.5mm protective body",
      "Wireless charging supported",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/puma.jpeg"],
    featured: false,
    available: true,
    stock: 16,
  },
  {
    id: "case-009",
    name: "Shadow Minimalist Silhouette Case",
    slug: "shadow-minimalist-silhouette-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Sleek noir silhouette graphic balancing high contrast black and ivory tones for a sophisticated urban edge.",
    details: [
      "Soft-touch matte velvet coating",
      "Slim profile that slides easily into pockets",
      "Scratch-shield surface protection",
      "All-port easy access cutouts",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/shadow.jpeg"],
    featured: false,
    available: true,
    stock: 20,
  },
  {
    id: "case-010",
    name: "Sunflowers Modern Impressionist Case",
    slug: "sunflowers-modern-impressionist-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Vibrant golden sunflowers inspired by classic post-impressionism with a modern pop color palette.",
    details: [
      "Textured oil-paint feel finish",
      "Heavy-duty shockproof corners",
      "Bezel defense for camera and screen",
      "Eco-friendly recyclable materials",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/sunflowers.jpeg"],
    featured: true,
    available: true,
    stock: 24,
    isNew: true,
  },
  {
    id: "case-011",
    name: "The Roar Royal Tiger Case",
    slug: "the-roar-royal-tiger-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Mesmerizing wild tiger pop-art portrait expressing raw power and vibrant color depth.",
    details: [
      "Ultra-durable anti-scratch back",
      "Enhanced corner drop dampers",
      "Precise speaker and port cutouts",
      "Premium satin matte texture",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/the-roar.jpeg"],
    featured: true,
    available: true,
    stock: 18,
    isNew: true,
  },
  {
    id: "case-012",
    name: "Samurai Warrior Pop Case",
    slug: "samurai-warrior-pop-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Epic traditional Japanese samurai warrior graphic stylized with contemporary pop comic hues.",
    details: [
      "Impact-resistant polycarbonate shell",
      "Full-wrap sublimation artwork",
      "Reinforced bumper protection",
      "MagSafe & wireless charging ready",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/warrior.jpeg"],
    featured: true,
    available: true,
    stock: 15,
    isNew: true,
  },
  {
    id: "case-013",
    name: "Astral Neon Horizon Case",
    slug: "astral-neon-horizon-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Vibrant synthwave & astral neon graphic phone case featuring futuristic landscape artwork with dual-layer shockproof defense.",
    details: [
      "Impact-resistant dual layer polycarbonate shell",
      "Vivid fade-proof UV sublimation print",
      "Raised 1.2mm camera bezel & screen rim",
      "Wireless charging & MagSafe compatible",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-1.png"],
    featured: true,
    available: true,
    stock: 20,
    isNew: true,
  },
  {
    id: "case-014",
    name: "Golden Blossom Botanical Case",
    slug: "golden-blossom-botanical-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Elegant gilded floral motif with gold accents against a deep aesthetic backdrop, offering sleek protection with luxury styling.",
    details: [
      "Anti-scratch glossy coat",
      "Shock-absorbing TPU bumper frame",
      "Slim tactile grip profile",
      "Precision cutouts for all ports and buttons",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-2.png"],
    featured: true,
    available: true,
    stock: 18,
    isNew: true,
  },
  {
    id: "case-015",
    name: "Velvet Midnight Flora Case",
    slug: "velvet-midnight-flora-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Dark botanical blooms with deep jewel tones designed for an enchanting, modern feminine aesthetic.",
    details: [
      "High-density color saturation",
      "Dual-layer drop protection",
      "Matte soft-touch finish",
      "Full camera module protection",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-3.png"],
    featured: false,
    available: true,
    stock: 22,
    isNew: true,
  },
  {
    id: "case-016",
    name: "Aurora Pastel Dream Case",
    slug: "aurora-pastel-dream-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Soothing aurora borealis pastel hues flowing gracefully for an ethereal, tranquil look with durable edge protection.",
    details: [
      "Smooth satin anti-fingerprint surface",
      "Air-cushioned corners for impact resistance",
      "Lightweight non-bulky form factor",
      "MagSafe charging supported",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-4.png"],
    featured: true,
    available: true,
    stock: 25,
    isNew: true,
  },
  {
    id: "case-017",
    name: "Prism Quartz Luxe Case",
    slug: "prism-quartz-luxe-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Geometric crystal facets with shimmering refraction effects, turning your phone into an exquisite statement accessory.",
    details: [
      "High-gloss crystalline protective shield",
      "Enhanced corner drop bumpers",
      "Tactile responsive chrome buttons",
      "Scratch and scuff resistant",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-5.png"],
    featured: false,
    available: true,
    stock: 16,
    isNew: true,
  },
  {
    id: "case-018",
    name: "Cosmic Starlight Fantasy Case",
    slug: "cosmic-starlight-fantasy-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Mesmerizing deep space galaxy artwork speckled with sparkling stardust constellations and nebula clouds.",
    details: [
      "Ultra-vivid deep color dye sublimation",
      "Dual-layer shockproof inner silicone",
      "Raised lip for screen defense",
      "Wireless charging friendly",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-7.png"],
    featured: false,
    available: true,
    stock: 19,
    isNew: true,
  },
  {
    id: "case-019",
    name: "Retro Glitch Wave Case",
    slug: "retro-glitch-wave-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "90s vaporwave digital glitch aesthetics with high-contrast electric neon hues for edgy pop style.",
    details: [
      "Anti-slip textured perimeter",
      "Reinforced corner impact cushions",
      "Durable scratch-proof polycarbonate",
      "Precise camera ring cutout",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-8.png"],
    featured: true,
    available: true,
    stock: 24,
    isNew: true,
  },
  {
    id: "case-020",
    name: "Rose Gold Marble Luxe Case",
    slug: "rose-gold-marble-luxe-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Classic Italian Carrara marble texture veined with warm rose gold metallic ribbons for understated opulence.",
    details: [
      "Glossy ceramic-look finish",
      "Shockproof polycarbonate shell",
      "Lightweight sleek design",
      "Comfortable ergonomic grip",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-9.jpeg"],
    featured: true,
    available: true,
    stock: 30,
    isNew: true,
  },
  {
    id: "case-021",
    name: "Sunburst Yellow Pop Case",
    slug: "sunburst-yellow-pop-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Radiant sunny yellow pop-art illustration bringing joyful warmth and energetic vibes to your daily routine.",
    details: [
      "Fade-proof high-gloss vibrant coat",
      "Dual-layer shock resistance",
      "Raised 1.2mm camera border",
      "Slim and pocket-friendly",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-11.jpeg"],
    featured: true,
    available: true,
    stock: 22,
    isNew: true,
  },
  {
    id: "case-022",
    name: "Lavender Breeze Aesthetic Case",
    slug: "lavender-breeze-aesthetic-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Gentle pastel lilac and lavender botanical sprigs designed for minimalists who love soft French countryside chic.",
    details: [
      "Soft matte texture with anti-slip grip",
      "Shockproof TPU edges",
      "Scratch and stain resistant",
      "Wireless charging compatible",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-12.jpeg"],
    featured: false,
    available: true,
    stock: 25,
    isNew: true,
  },
  {
    id: "case-023",
    name: "Cherry Blossom Sakura Case",
    slug: "cherry-blossom-sakura-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Delicate pink Japanese sakura blossoms drifting across a serene ivory sky with subtle oriental brush details.",
    details: [
      "Glossy crystal scratch protection",
      "Reinforced corner drop protection",
      "Raised camera bezel guard",
      "Non-yellowing premium TPU",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-14.jpeg"],
    featured: true,
    available: true,
    stock: 28,
    isNew: true,
  },
  {
    id: "case-024",
    name: "Celestial Moon Dust Case",
    slug: "celestial-moon-dust-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Enchanting lunar phase artwork with gold celestial charts and silver shimmer over deep navy skies.",
    details: [
      "Glossy metallic-effect finish",
      "Dual-layer tough drop cushion",
      "Camera lens safety border",
      "Non-fade archival color technology",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-19.jpeg"],
    featured: false,
    available: true,
    stock: 22,
    isNew: true,
  },
  {
    id: "case-025",
    name: "Desert Mirage Gradient Case",
    slug: "desert-mirage-gradient-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Warm desert sunset hues transitioning seamlessly from terracotta rose to golden saffron amber.",
    details: [
      "Velvet matte anti-glare coat",
      "Shockproof TPU perimeter",
      "Ultra-slim and featherlight",
      "Precision speaker port cutouts",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-20.jpeg"],
    featured: true,
    available: true,
    stock: 20,
    isNew: true,
  },
  {
    id: "case-026",
    name: "Retro Cassette Funky Case",
    slug: "retro-cassette-funky-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Nostalgic 80s mixtape audio cassette graphic bringing vintage analog charm to your modern device.",
    details: [
      "Textured vintage cassette details",
      "Rigid impact-resistant backplate",
      "Raised camera surround",
      "MagSafe charging compatible",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-21.jpeg"],
    featured: false,
    available: true,
    stock: 17,
    isNew: true,
  },
  {
    id: "case-027",
    name: "Ocean Tide Abstract Case",
    slug: "ocean-tide-abstract-case",
    category: "cases",
    subcategory: "pop-art-funky",
    price: 1900,
    originalPrice: 2000,
    currency: "PKR",
    description:
      "Deep sea azure and cerulean blue acrylic pour effect with frothy coastal wave accents.",
    details: [
      "High-gloss watery sheen finish",
      "Air-cushion impact mitigation",
      "Anti-scratch polymer back",
      "Responsive button covers",
    ],
    sizes: [
      "iPhone 13 / 14",
      "iPhone 14 Pro Max",
      "iPhone 15 / 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16 Pro / Pro Max",
      "Samsung S23 / S24 Ultra",
    ],
    colors: ["Glossy Finish", "Matte Finish", "Tough Shockproof"],
    images: ["/products/cases/COVERS/cover-22.jpeg"],
    featured: true,
    available: true,
    stock: 25,
    isNew: true,
  },
  {
    id: "soap-001",
    name: "Rose Blossom Glow Jelly Soap",
    slug: "rose-blossom-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Handcrafted bouncy jelly soap infused with pure organic damask rose water and hydrating aloe vera for a soothing, floral cleanse.",
    details: [
      "Custom shape & personalized scent available",
      "Infused with organic rose extracts & aloe vera",
      "Gentle sulfate-free & vegan formulation",
      "Ultra-hydrating bouncy jelly texture",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Rose Pink", "Customized Color"],
    images: ["/products/skincare/jelly-soaps/1.jpeg"],
    featured: false,
    available: true,
    stock: 25,
  },
  {
    id: "soap-002",
    name: "Honey Amber Botanical Jelly Soap",
    slug: "honey-amber-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "A golden, nutrient-rich jelly soap crafted with natural honey extracts and sweet almond oil to restore skin softness and natural glow.",
    details: [
      "Enriched with raw organic honey & vitamin E",
      "Ultra-nourishing for dry and sensitive skin",
      "Customized initials / lettering on request",
      "Moisturizing plant glycerin base",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Golden Amber", "Warm Honey"],
    images: ["/products/skincare/jelly-soaps/2.jpeg"],
    featured: false,
    available: true,
    stock: 20,
  },
  {
    id: "soap-003",
    name: "Lavender Breeze Relaxing Jelly Soap",
    slug: "lavender-breeze-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Calming French lavender essential oil infused into a bouncy jelly bar that relieves daily stress while leaving skin delicately perfumed.",
    details: [
      "Therapeutic lavender essential oil",
      "Calms skin redness & irritation",
      "Bouncy squishy jelly lather",
      "Paraben & cruelty free",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Lavender Purple", "Pastel Lilac"],
    images: ["/products/skincare/jelly-soaps/3.jpeg"],
    featured: false,
    available: true,
    stock: 18,
  },
  {
    id: "soap-004",
    name: "Citrus Sunshine Brightening Jelly Soap",
    slug: "citrus-sunshine-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Zesty sweet orange and lemon zest botanicals packed with vitamin C to refresh tired skin and boost natural radiance.",
    details: [
      "Vitamin C & citrus fruit oils",
      "Energizing daytime cleanser",
      "Custom colors & custom packaging",
      "100% handmade in small batches",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Citrus Orange", "Sunny Yellow"],
    images: ["/products/skincare/jelly-soaps/4.jpeg"],
    featured: false,
    available: true,
    stock: 22,
  },
  {
    id: "soap-005",
    name: "Ocean Mist Hydrating Jelly Soap",
    slug: "ocean-mist-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Refreshing marine mineral jelly soap that cleanses deep into pores and leaves your skin feeling cool, hydrated, and silky smooth.",
    details: [
      "Marine botanicals & sea kelp extract",
      "Hydrating barrier protection",
      "Crisp aquatic ocean fragrance",
      "Gentle everyday body & face bar",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Ocean Blue", "Turquoise Aqua"],
    images: ["/products/skincare/jelly-soaps/5.jpeg"],
    featured: false,
    available: true,
    stock: 15,
  },
  {
    id: "soap-006",
    name: "Blush Peony Artisan Jelly Soap",
    slug: "blush-peony-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Artisanal sculpted jelly soap blooming with fresh peony petals and hydrating jojoba beads for a luxurious spa-at-home experience.",
    details: [
      "Artisan sculpted flower detailing",
      "Infused with floral peony nectar",
      "Ideal luxury gift or bridal favor",
      "Rich hydrating foam",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Blush Pink", "Soft Rose"],
    images: ["/products/skincare/jelly-soaps/6.jpeg"],
    featured: false,
    available: true,
    stock: 12,
  },
  {
    id: "soap-007",
    name: "Signature Botanical Jelly Soaps (Set of 6)",
    slug: "signature-layora-jelly-soap-set",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 1500,
    currency: "PKR",
    description:
      "The complete 6-piece LAYORA botanical collection: an exquisite set of assorted artisanal jelly soaps crafted with nourishing plant extracts and luxury packaging.",
    details: [
      "Includes full set of 6 assorted handcrafted jelly soaps",
      "Features Lotus, Rose, Botanical, and Citrus formulations",
      "Deluxe gift packaging with satin ribbon included",
      "Gentle, hydrating, and 100% vegan ingredients",
    ],
    sizes: ["Complete Set of 6 Jelly Soaps", "Deluxe Ribbon Gift Box"],
    colors: ["Signature Multi-Color Assortment"],
    images: ["/products/skincare/jelly-soaps/7.jpeg"],
    featured: false,
    available: true,
    stock: 20,
  },
  {
    id: "soap-008",
    name: "Ocean Fresh Botanical Jelly Soap",
    slug: "ocean-fresh-botanical-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Invigorating botanical extracts and olive oil that gently clarify skin and provide a cooling post-wash glow.",
    details: [
      "Spearmint & organic olive oils",
      "Cooling sensation & pore clarifying",
      "Custom lettering & name tags",
      "100% vegan formula",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Cool Olive", "Emerald Green"],
    images: ["/products/skincare/jelly-soaps/8.jpeg"],
    featured: false,
    available: true,
    stock: 19,
  },
  {
    id: "soap-009",
    name: "Berry Fusion Fruity Jelly Soap",
    slug: "berry-fusion-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Sweet summer raspberry, blackberry, and strawberry extract blend packed with antioxidants to protect and nourish your skin.",
    details: [
      "Real berry seed extract & antioxidants",
      "Sweet fruity bubblegum fragrance",
      "Fun bouncy jelly feel",
      "Gentle for all skin types",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Berry Magenta", "Deep Ruby"],
    images: ["/products/skincare/jelly-soaps/9.jpeg"],
    featured: false,
    available: true,
    stock: 14,
  },
  {
    id: "soap-010",
    name: "Custom Monogram Initial Jelly Soap",
    slug: "custom-monogram-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Personalized luxury jelly soap handcrafted with your chosen monogram, initials, or name. Perfect for birthdays, weddings, and gifts.",
    details: [
      "Custom initials / monogram engraved",
      "Choose your favorite scent & color",
      "Includes luxury gift packaging",
      "Handmade with natural plant oils",
    ],
    sizes: ["Personalized Bar (120g)"],
    colors: ["Customized on Order", "Pastel Multi-color"],
    images: ["/products/skincare/jelly-soaps/10.jpeg"],
    featured: false,
    available: true,
    stock: 30,
  },
  {
    id: "soap-011",
    name: "Crystal Bloom Transparent Jelly Soap",
    slug: "crystal-bloom-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Ultra-clear crystal glass-like jelly soap featuring embedded botanical petals and a light floral jasmine scent.",
    details: [
      "Crystal-clear plant jelly formulation",
      "Embedded dried organic petals",
      "Delicate jasmine & neroli aroma",
      "Deep moisture retention",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Crystal Clear", "Translucent Pink"],
    images: ["/products/skincare/jelly-soaps/11.jpeg"],
    featured: false,
    available: true,
    stock: 10,
  },
  {
    id: "soap-012",
    name: "Ruby Velvet Exfoliating Jelly Soap",
    slug: "ruby-velvet-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "A deep ruby red jelly bar infused with natural pomegranate seed scrub particles for gentle body exfoliation and radiant smoothness.",
    details: [
      "Gentle natural botanical scrub",
      "Pomegranate & cranberry seed oil",
      "Leaves skin silky smooth & glowing",
      "Paraben free",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Ruby Red", "Deep Crimson"],
    images: ["/products/skincare/jelly-soaps/12.jpeg"],
    featured: false,
    available: true,
    stock: 15,
  },
  {
    id: "soap-013",
    name: "Sweet Peach Nourishing Jelly Soap",
    slug: "sweet-peach-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Juicy sweet peach and shea butter jelly soap that leaves a delicious sun-ripened scent and long-lasting velvety hydration.",
    details: [
      "Peach fruit extract & shea butter",
      "Sweet succulent peach aroma",
      "Extra gentle for daily face & body care",
      "100% cruelty-free",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Peach Coral", "Pastel Apricot"],
    images: ["/products/skincare/jelly-soaps/13.jpeg"],
    featured: false,
    available: true,
    stock: 18,
  },
  {
    id: "soap-014",
    name: "Rose Blossom Artisan Botanical Jelly Soap",
    slug: "rose-blossom-artisan-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Delicately crafted rose shaped jelly soap enriched with natural damask rose extract, aloe vera, green tea, and vitamin E for glowing skin.",
    details: [
      "Rose extract, aloe vera & glycerin enriched",
      "Gentle cleansing & deep hydration",
      "Enchanting aromatic rose scent",
      "Handcrafted with love",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Rose Petal Pink"],
    images: ["/products/skincare/jelly-soaps/14.jpeg"],
    featured: false,
    available: true,
    stock: 25,
  },
  {
    id: "soap-015",
    name: "Ocean Fresh Smooth Oval Jelly Soap",
    slug: "ocean-fresh-oval-jelly-soap",
    category: "skincare",
    subcategory: "jelly-soaps",
    price: 400,
    currency: "PKR",
    description:
      "Refreshing ocean blue oval jelly soap made with nourishing oils, gentle on skin and leaves a refreshing aromatic fragrance.",
    details: [
      "Deep moisture locking & revitalizing",
      "Nourishing premium oils & ingredients",
      "A touch of luxury for everyday skincare",
      "100% gentle and cruelty-free",
    ],
    sizes: ["Single Bar (100g)"],
    colors: ["Ocean Blue"],
    images: ["/products/skincare/jelly-soaps/15.jpeg"],
    featured: false,
    available: true,
    stock: 20,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "accessories" || category === "cases") {
    return products.filter(
      (p) => p.category === "accessories" || p.category === "cases"
    );
  }
  return products.filter((p) => p.category === category);
}

export function getProductsBySubcategory(
  category: string,
  subcategory: string
): Product[] {
  return products.filter(
    (p) => p.category === category && p.subcategory === subcategory
  );
}

export function getFeaturedProducts(limit?: number): Product[] {
  const featured = products.filter((p) => p.featured);
  return typeof limit === "number" ? featured.slice(0, limit) : featured;
}

export function getFeaturedBySubcategory(
  subcategory: string,
  limit = 4
): Product[] {
  return products
    .filter((p) => p.subcategory === subcategory)
    .slice(0, limit);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

